-- Create a table to store user plans
create table if not exists user_plans (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  units text,
  gender text,
  age int,
  weight numeric,
  height numeric,
  goal text
);

-- (Optional) Disable RLS for now if anonymous access is required
-- alter table user_plans disable row level security;

-- OR Create a policy to allow anonymous inserts
-- create policy "Allow anonymous inserts" on user_plans for insert with check (true);
